### ISSUE TITLE
Video's not streaming

### ISSUE THREAD

**Issue by dare-jbw** [adam-werner/Our.Umbraco.StorageProviders.AWSS3#8]
I am almost certain this was working the other day, but I am having an issue now where uploaded video content over a couple of MBs don't seem to be streaming back anymore.

I've gone through the code and I don't seem to be getting any notable errors, except the request seems to cancel out, and a cancelation token is sent. 

This is what I get in the network trace. 
![image](https://github.com/adam-werner/Our.Umbraco.StorageProviders.AWSS3/assets/114588624/bfb3c5a3-93fb-4713-8266-4c92c3048d06)

It does sometimes show the 206 request with no cancellation but still doesn't stream the video content. I've tested this one on two Umbraco installations and a fresh installation. The issue persists on all of them. 

EDIT:
I thought this was working before but it turns out it was defaulting to some media items that had been stored in the media directory located with the site. Renaming/deleting those files forces it to then go to S3 which doesn't seem to work/stream properly.

**Comment by adam-werner** [comment]
@dare-jbw I apologize for the delay and I do see your pull request that looks to resolve the issue.  

As I look to bring in the code, I would be interested in seeing what I could do to reproduce the issue -- is there a size or length of the video that would seem to trigger the issue you saw?

Thank you again!

**Comment by dare-jbw** [comment]
@adam-werner no worries at all, thanks for having a look.

I believe it was for any files bigger then 15-20mb. Most of our videos are 100mb+ and noticed that all of those where not working.

This environment was running on kestrel, running in .net6 and Umbraco 10.5 if that helps. Noticed the issue when running locally and on the hosted versions (hosted version are running in eks using docker images). 

Let me know if there is any other info you need.

**Comment by adam-werner** [comment]
@dare-jbw Thank you!  Your update has been included in the v1.3.0 of the package.
